name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-2
      AWS_ACCOUNT_ID: "856021348734"
      ECR_REPOSITORY: codereview-ai
      IMAGE_URI: 856021348734.dkr.ecr.us-east-2.amazonaws.com/codereview-ai

    services:
      pgvector:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_USER: naveen
          POSTGRES_PASSWORD: codereview
          POSTGRES_DB: codereview_ai
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Run tests
        run: ./mvnw test
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Build jar
        run: ./mvnw clean package -DskipTests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t $IMAGE_URI:latest .

      - name: Push Docker image
        run: docker push $IMAGE_URI:latest

      - name: Deploy to ECS
        run: aws ecs update-service --cluster fortune-cluster --service codereview-ai-service --force-new-deployment --region $AWS_REGION
